import numpy as np
from itertools import combinations

class GlauberDynamics:                                                              #questa potrebbe essere solo la funzione pura che fa TPM, ma per ora va bene così
    
        def __init__(self, system, TPM = None, flips=1):
            '''
            Parameters
            ----------
            system : class
                Istance of IsingSystem.

            flips : int, optional
                Number of spin that are flipped at time during the evolution of the 
                system. The default is 1.

            '''
            self.system = system
            self.flips = flips
            
            if TPM is None: 
                self.TPM = self.build_TPM()
            else:
                self.TPM =TPM
            
            
        def build_TPM(self):
            '''
            Generate the transition probability matrix for a system with N binary neurons 
            interacting through the J matrix. Neuron states can either be -1 or 1.
            The TPM coefficients are the probabilities, given a current state, 
            to select a target configuration and to evolve into it. 
            The probaility for the selection of the target configuration is the 
            uniform distribution, where each target configuration has a chance 1/N_target
            to be selected and N_target is the number of all configuration in which the 
            current state can evolve. The probability that the proposed transition is 
            accepted follows the Glauber formula. 
            
            Parameters                                                          # se teniamo il self questo si elimina
            ----------
            N : int
                Number of neurons composing the system.
            J : np.ndarray
                Interaction matrix.
            beta : float, optional
                It is the inverse of temperature and it measures the degree of
                environmental noise. The default is 1.
            flips : int, optional
                Number of spin that are flipped at time during the evolution of the 
                system. The default is 1.

            Returns
            -------
            TPM : np.ndarray
                Transition probability matrix .
            all_configs : np.ndarray
                List of all configurations of the system.
            config_to_idx : dict
                All configurations of the system are numerated from 0 to 2^N-1.

            '''
            N = self.system.N
            J = self.system.J
            beta = self.system.beta
            n_configs = self.system.n_configs                                   # vediamo quante volte lo usiamo n_configs perchè potremmo direttamente calcolarlo
            all_configs = self.system.configs 
            
            # indexing configurations thorough a dictionary
            config_to_idx = {tuple(config): i 
                             for i, config in enumerate(all_configs)}
            
            # listing all possible ways to make 'flips' flips over 'N' spins 
            # 'flips' is completely general 
            # here we assume that len(flips) = 1

            flip_indices = list(combinations(range(N), self.flips))
            
            
            TPM = np.zeros((n_configs, n_configs))
            
            for i, config in enumerate(all_configs):
                config = np.array(config)

                # get the local fields generated by each 'config' over the
                # individual spins 
                fields = J @ config.T
                
                # find the configurations that differ from 'config' of 'flips' flips  
                for indices in flip_indices:
                    new_config = config.copy()
                    new_config[list(indices)] *= -1 
                    j = config_to_idx[tuple(new_config)]
                    
                    if j>i:
                        if self.flips == 1:
                            neuron_idx = indices[0]
                            delta_E = 2 * config[neuron_idx] * fields[neuron_idx]
                          
                        else:
                            # For multiple flips, need to substract the total energies
                            E_current = self.system.energy_config(config)
                            E_new = self.system.energy_config(new_config)
                            delta_E = E_new - E_current
                      
                        # Glauber probability
                        TPM[i, j] = 1.0 / (1.0 + np.exp(beta * delta_E))
                
                    else: 
                        TPM[i, j] = 1 - TPM[j, i] # this is =  1.0 / (1.0 + np.exp(-beta * delta_E))
            
            for i in range(len(all_configs)):
                # normalization_factoralized
                TPM[i, :] /= len(flip_indices)  #uniform selection probability and len(flip_indices) is the number of possible final states
                # Add diagonal coefficients
                TPM[i,i]=1-sum(TPM[i,:])    #1-the probability to go somewhere  
            
            return TPM
        
        def evolution(self, p, step = 1):
            '''
            Evolves the array 'p' of a given number of steps
            by multiplying it with the TPM stored in GlauberDynamics

            Parameters
            ----------
            p : 1D array
                
            step : int, optional
                Number of time steps evolution. The default is 1.

            Returns
            -------
            array
                The evolved array.

            '''
            return p @ np.linalg.matrix_power(self.TPM, step)
        
        

        
